<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="NuGet.Packaging" Version="6.14.3" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="8.0.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tolk.BusinessLogic.Tests\Tolk.BusinessLogic.Tests.csproj" />
    <ProjectReference Include="..\Tolk.Web\Tolk.Web.csproj" />
  </ItemGroup>

</Project>
