
CREATE TABLE #Languages(
	[LanguageId] [int] NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Active] [bit] NOT NULL DEFAULT ((0)),
	[ISO_639_1_Code] [nvarchar](2) NULL,
	[TellusName] [nvarchar](100) NULL
	)

INSERT #Languages (LanguageId, Name, ISO_639_1_Code, TellusName, Active)
	VALUES 
(1, 'Abchaziska', 'ab', '', 1),
(2, 'Afan Oromo', 'om', '', 1),
(3, 'Afar', 'aa', '', 1),
(4, 'Afrikaans', 'af', '', 1),
(5, 'Albanska', 'sq', 'albanska', 1),
(6, 'Amhariska', 'am', '', 1),
(7, 'Arabiska', 'ar', 'arabiska', 1),
(8, 'Arameiska/Syriska', '', 'arameiska/syriska', 1),
(9, 'Armeniska', 'hy', 'armeniska', 1),
(10, 'Assamesiska', 'as', '', 1),
(11, 'Aymara', 'ay', '', 1),
(12, 'Azerbajdzjanska', 'az', 'azerbajdzjanska', 1),
(13, 'Basjkiriska', 'ba', '', 1),
(14, 'Baskiska', 'eu', '', 1),
(15, 'Bengali', 'bn', '', 1),
(16, 'Bihari', 'bh', '', 1),
(17, 'Bislama', 'bi', '', 1),
(18, 'Bosniska/Kroatiska/Serbiska', '', 'bosniska/kroatiska/serbiska', 1),
(19, 'Bretonska', 'br', '', 1),
(20, 'Bulgariska', 'bg', 'bulgariska', 1),
(21, 'Burmesiska', 'my', '', 1),
(22, 'Danska', 'da', 'danska', 1),
(23, 'Dari', '', 'dari', 1),
(24, 'Dzongkha', 'dz', '', 1),
(25, 'Engelska', 'en', 'engelska', 1),
(26, 'Esperanto', 'eo', '', 1),
(27, 'Estniska', 'et', 'estniska', 1),
(28, 'Fijianska', 'fj', '', 1),
(29, 'Finska', 'fi', 'finska', 1),
(30, 'Franska', 'fr', 'franska', 1),
(31, 'Frisiska', 'fy', '', 1),
(32, 'Färöiska', 'fo', '', 1),
(33, 'Gaeliska', 'gd', '', 1),
(34, 'Galiciska', 'gl', '', 1),
(35, 'Georgiska', 'ka', 'georgiska', 1),
(36, 'Grekiska', 'el', 'grekiska', 1),
(37, 'Grönländska', 'kl', '', 1),
(38, 'Guarani', 'gn', '', 1),
(39, 'Gujarati', 'gu', '', 1),
(40, 'Hausa', 'ha', '', 1),
(41, 'Hebreiska', 'he', 'hebreiska', 1),
(42, 'Hindi', 'hi', 'hindi', 1),
(43, 'Indonesiska', 'id', 'indonesiska', 1),
(44, 'Interlingua', 'ia', '', 1),
(45, 'Interlingue', 'ie', '', 1),
(46, 'Inuktitut', 'iu', '', 1),
(47, 'Iñupiaq', 'ik', '', 1),
(48, 'Iriska', 'ga', '', 1),
(49, 'Isländska', 'is', 'isländska', 1),
(50, 'Italienska', 'it', 'italienska', 1),
(51, 'Japanska', 'ja', 'japanska', 1),
(52, 'Javanesiska', 'jv', '', 1),
(53, 'Jiddisch', 'yi', '', 1),
(54, 'Kambodjanska', 'km', '', 1),
(55, 'Kannada', 'kn', '', 1),
(56, 'Kantonesiska', '', 'kantonesiska', 1),
(57, 'Kashmiri', 'ks', '', 1),
(58, 'Katalanska', 'ca', '', 1),
(59, 'Kazakiska', 'kk', '', 1),
(60, 'Kinesiska', 'zh', 'kinesiska', 1),
(61, 'Kinyarwanda', 'rw', '', 1),
(62, 'Kirgiziska', 'ky', '', 1),
(63, 'Kirundi', 'rn', 'kirundi', 1),
(64, 'Koreanska', 'ko', 'koreanska', 1),
(65, 'Korsikanska', 'co', '', 1),
(66, 'Kymriska', 'cy', '', 1),
(67, 'Laotiska', 'lo', '', 1),
(68, 'Latin', 'la', '', 1),
(69, 'Lettiska', 'lv', 'lettiska', 1),
(70, 'Lingala', 'ln', '', 1),
(71, 'Litauiska', 'lt', 'litauiska', 1),
(72, 'Madagaskiska', 'mg', '', 1),
(73, 'Makedonska', 'mk', 'makedonska', 1),
(74, 'Malajiska', 'ms', '', 1),
(75, 'Malayalam', 'ml', '', 1),
(76, 'Maltesiska', 'mt', '', 1),
(77, 'Maori', 'mi', '', 1),
(78, 'Marathi', 'mr', '', 1),
(79, 'Meänkieli', '', 'meänkieli', 1),
(80, 'Moldaviska', 'mo', '', 1),
(81, 'Mongoliska', 'mn', 'mongoliska', 1),
(82, 'Nauriska', 'na', '', 1),
(83, 'Nederländska', 'nl', 'nederländska', 1),
(84, 'Nepali', 'ne', 'nepali', 1),
(85, 'Nordkurdiska', '', 'nordkurdiska', 1),
(86, 'Norska', 'no', 'norska', 1),
(87, 'Nyanja', 'ny', '', 1),
(88, 'Occitanska', 'oc', '', 1),
(89, 'Oriya', 'or', '', 1),
(90, 'Pashto', 'ps', 'pashto', 1),
(91, 'Persiska', 'fa', 'persiska', 1),
(92, 'Polska', 'pl', 'polska', 1),
(93, 'Portugisiska', 'pt', 'portugisiska', 1),
(94, 'Punjabi', 'pa', '', 1),
(95, 'Quechua', 'qu', '', 1),
(96, 'Rikskinesiska', '', 'rikskinesiska', 1),
(97, 'Romska', '', 'romska', 1),
(98, 'Rumantsch', 'rm', '', 1),
(99, 'Rumänska', 'ro', 'rumänska', 1),
(100, 'Ryska', 'ru', 'ryska', 1),
(101, 'Samiska (Nordsamiska)', '', 'samiska (nordsamiska)', 1),
(102, 'Samoanska', 'sm', '', 1),
(103, 'Sangho', 'sg', '', 1),
(104, 'Sanskrit', 'sa', '', 1),
(105, 'Sardiska', 'sc', '', 1),
(106, 'Serbokroatiska', 'sh', 'bosniska/kroatiska/serbiska', 1),
(107, 'Sesotho', 'st', '', 1),
(108, 'Setswana', 'tn', '', 1),
(109, 'Shona', 'sn', '', 1),
(110, 'Sindhi', 'sd', '', 1),
(111, 'Singalesiska', 'si', '', 1),
(112, 'Siswati', 'ss', '', 1),
(113, 'Slovakiska', 'sk', 'slovakiska', 1),
(114, 'Slovenska', 'sl', 'slovenska', 1),
(115, 'Somaliska', 'so', 'somaliska', 1),
(116, 'Spanska', 'es', 'spanska', 1),
(117, 'Sundanesiska', 'su', '', 1),
(118, 'Swahili', 'sw', 'swahili', 1),
(119, 'Svenska', 'sv', 'svenska', 1),
(120, 'Sydkurdiska', '', 'sydkurdiska', 1),
(121, 'Tadzjikiska', 'tg', '', 1),
(122, 'Tagalog', 'tl', 'tagalog', 1),
(123, 'Tamil', 'ta', '', 1),
(124, 'Tatariska', 'tt', '', 1),
(125, 'Teckenspråk', '', 'teckenspråk', 1),
(126, 'Telugu', 'te', '', 1),
(127, 'Thailändska', 'th', 'thai', 1),
(128, 'Tibetanska', 'bo', '', 1),
(129, 'Tigrinska', 'ti', 'tigrinska', 1),
(130, 'Tjeckiska', 'cs', 'tjeckiska', 1),
(131, 'Tjuvasjiska', 'cv', '', 1),
(132, 'Tonganska', 'to', '', 1),
(133, 'Tsonga', 'ts', '', 1),
(134, 'Turkiska', 'tr', 'turkiska', 1),
(135, 'Turkmenska', 'tk', '', 1),
(136, 'Twi', 'tw', '', 1),
(137, 'Tyska', 'de', 'tyska', 1),
(138, 'Uiguriska', 'ug', '', 1),
(139, 'Ukrainska', 'uk', 'ukrainska', 1),
(140, 'Ungerska', 'hu', 'ungerska', 1),
(141, 'Urdu', 'ur', 'urdu', 1),
(142, 'Uzbekiska', 'uz', 'uzbekiska', 1),
(143, 'Vietnamesiska', 'vi', 'vietnamesiska', 1),
(144, 'Vitryska', 'be', 'vitryska', 1),
(145, 'Volapük', 'vo', '', 1),
(146, 'Wolof', 'wo', '', 1),
(147, 'Xhosa', 'xh', '', 1),
(148, 'Yoruba', 'yo', '', 1),
(149, 'Zhuang', 'za', '', 1),
(150, 'Zulu', 'zu', '', 1),
(1000, 'Övrigt', '', '', 1)


SET IDENTITY_INSERT Languages ON

MERGE Languages dst
USING #Languages src
ON (src.LanguageId = dst.LanguageId)
WHEN MATCHED THEN
UPDATE SET dst.Name = src.Name, dst.Active = src.Active, dst.TellusName = src.Tellusname, dst.ISO_639_1_Code = src.ISO_639_1_Code
WHEN NOT MATCHED THEN
INSERT (LanguageId, Name, ISO_639_1_Code, TellusName, Active)
VALUES (src.LanguageId, src.Name, src.ISO_639_1_Code, src.TellusName, src.Active);

SET IDENTITY_INSERT Languages OFF

DROP TABLE #Languages